stages:
  - test

variables:
  DOCKER_IMAGE: node:14

default:
  tags:
    - docker

before_script:
  - docker pull $DOCKER_IMAGE || true

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE npm install
    - docker run $DOCKER_IMAGE npm test -- --coverage
  artifacts:
    reports:
      junit:
        - junit.xml
