image: docker:20.10.12
services:
  - name: docker:20.10.12-dind

before_script:
  - cd Backend
default:
  tags:
    - docker

stages:
  - test

tests:
  stage: test
  script:
    - docker build -t connectandexplorebackend:latest -f Dockerfile.test .
    - docker run connectandexplorebackend:latest
