image: node:latest

before_script:
  - wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - cd Backend

stages:
  - test

tests:
  stage: test
  script:
    - npm install
    - npm test -- --coverage
