image: node:latest

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - cd Backend

stages:
  - test

tests:
  stage: test
  script:
    - npm install
    - npm test -- --coverage
